apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geth-testing-init

configMapGenerator:
  - name: geth-clique-scripts
    files:
      - ./check-for-chaindata.sh
  - name: geth-clique-env
    envs:
      - ./geth-clique.env
resources:
  - ./geth-clique-statefulset.yaml
  - ./geth-clique-data-volume.yaml
